GET http://localhost:8080/unifier/v0.1?npi=1467652149&model=CONCISE&target=CIGNA
Accept: application/json

###
GET https://public.fhir.flex.optum.com/R4/PractitionerRole?practitioner.identifier=1477502557
Accept: application/json

###
GET https://fhir.cigna.com/ProviderDirectory/v1/Organization/d16-8a2588dcb9d24284ae0a064f10d945df
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET https://fhir.cigna.com/ProviderDirectory/v1/Organization/d16-b7de958a2f958a69a3c55b7b87732653
Accept: application/json

###
GET http://localhost:8080/unifier/v0.1?npi=1477502557&model=CONCISE&primaryTaxonomy=207xx&target=KAISER_PERMANENTE
Accept: application/json

###

###
# NPI Registry
GET https://npiregistry.cms.hhs.gov/api?number=1477502557&enumeration_type=NPI-1&version=2.1
Accept: application/json

###
# /unifier/v0.1?npi=
GET http://localhost:8080/unifier/v0.1?npi=1477502557&model=NOT
Accept: application/json


###
# Cigna FHIR Test Query
GET https://fhir.cigna.com/ProviderDirectory/v1/Organization/dir-bOyy04aJxM2CFoKxRxtLKjNsfP4Afcx5cuJrc8x1up
Accept: application/json

